[workspace]
members = [
    "crates/server",
    "crates/core",
    "crates/transit",
    "crates/mobile",
    "crates/api-types",
    "crates/uniffi-bindgen",
    "tools/pmtiles-clip", "tools/mountain-kml-parser", "tools/osm-landmass",
]
resolver = "2"
